-- Thinking Council — Session Log Schema
-- Owner: Walid Saleh
-- Version: 1.1
--
-- Self-contained SQLite database for Council session research data.
-- Independent of ChiefOS's chiefos.db (different machine, different purpose).
--
-- Hermes auto-applies this schema on first run if council_sessions.db is missing.
-- Manual setup: sqlite3 ./data/council_sessions.db < ./data/schema.sql

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;   -- better for concurrent reads (research queries) during writes

-- ─────────────────────────────────────────────────────────────
-- Main session table
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS council_sessions (
    session_id              TEXT PRIMARY KEY,             -- UUID generated by Hermes
    timestamp               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_prompt             TEXT NOT NULL,
    triage_decision         TEXT NOT NULL,                -- 'proceed' | 'single_pass' | 'clarify' | 'aborted'

    -- Panelist outputs (raw, pre-anonymization, JSON object keyed by role)
    panelist_outputs        TEXT,                         -- JSON: {"analyst": "...", "generalist": "...", ...}

    -- Anonymization label map (internal — never surfaced to user)
    label_map               TEXT,                         -- JSON: {"panelist_1": "skeptic", ...}

    -- Critiques (JSON array of 8 critique objects)
    critiques               TEXT,                         -- JSON: [{"critic": "analyst", "target": "panelist_2", "type": "assigned", "text": "..."}, ...]

    -- Chairman output
    chairman_synthesis      TEXT,                         -- the full structured response (Answer / Reasoning / Dissent / Open questions)
    dissent_present         BOOLEAN DEFAULT 0,            -- true if Chairman surfaced genuine panel disagreement
    chairman_departure_flagged BOOLEAN DEFAULT 0,         -- true if Chairman flagged synthesis departure from all panelists

    -- Operational metrics
    total_tokens            INTEGER,                      -- sum across all model calls
    estimated_cost_usd      REAL,                         -- computed at session close
    duration_seconds        REAL,                         -- wall-clock from invocation to synthesis return

    -- Per-stage cost breakdown (for budget pacing audit)
    cost_triage_usd         REAL DEFAULT 0,
    cost_delegate_usd       REAL DEFAULT 0,
    cost_anonymize_usd      REAL DEFAULT 0,
    cost_critique_usd       REAL DEFAULT 0,
    cost_synthesize_usd     REAL DEFAULT 0,

    -- Failure / abort tracking
    aborted_at_stage        TEXT,                         -- NULL if completed; stage_id if aborted
    abort_reason            TEXT,                         -- NULL if completed; reason string if aborted
    panelists_completed     INTEGER DEFAULT 4,            -- < 4 if any panelist timed out

    -- Skill version (so future audits can correlate behavior changes with version bumps)
    skill_version           TEXT NOT NULL DEFAULT '1.1'
);

CREATE INDEX IF NOT EXISTS idx_sessions_timestamp ON council_sessions(timestamp);
CREATE INDEX IF NOT EXISTS idx_sessions_dissent ON council_sessions(dissent_present);
CREATE INDEX IF NOT EXISTS idx_sessions_departure ON council_sessions(chairman_departure_flagged);
CREATE INDEX IF NOT EXISTS idx_sessions_aborted ON council_sessions(aborted_at_stage);

-- ─────────────────────────────────────────────────────────────
-- Anonymization fidelity audit table (Tier 2 — populated post-hoc)
-- ─────────────────────────────────────────────────────────────
-- After ~10 sessions, run a separate Haiku call on each anonymized panelist
-- output asking "which model wrote this?" and log the guess + correctness here.
-- Above-chance accuracy (>25% for 4 panelists) means anonymization is failing.
CREATE TABLE IF NOT EXISTS anonymization_audits (
    audit_id                INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id              TEXT NOT NULL,
    panelist_label           TEXT NOT NULL,                -- 'panelist_1' through 'panelist_4'
    actual_role             TEXT NOT NULL,                -- 'analyst' | 'generalist' | 'skeptic' | 'visionary'
    guessed_role            TEXT,                         -- what the auditor model guessed
    correct                 BOOLEAN,                      -- did the guess match?
    audit_timestamp         DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES council_sessions(session_id)
);

CREATE INDEX IF NOT EXISTS idx_audits_session ON anonymization_audits(session_id);
CREATE INDEX IF NOT EXISTS idx_audits_correct ON anonymization_audits(correct);

-- ─────────────────────────────────────────────────────────────
-- Panelist latency tracking (for Tier 2 latency profiling)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stage_latencies (
    latency_id              INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id              TEXT NOT NULL,
    stage_id                TEXT NOT NULL,                -- 'triage' | 'delegate' | 'anonymize' | 'critique' | 'synthesize' | 'log'
    actor                   TEXT,                         -- agent name, NULL for runtime stages
    duration_seconds        REAL NOT NULL,
    FOREIGN KEY (session_id) REFERENCES council_sessions(session_id)
);

CREATE INDEX IF NOT EXISTS idx_latencies_session ON stage_latencies(session_id);
CREATE INDEX IF NOT EXISTS idx_latencies_stage ON stage_latencies(stage_id);
CREATE INDEX IF NOT EXISTS idx_latencies_actor ON stage_latencies(actor);

-- ─────────────────────────────────────────────────────────────
-- Useful research views
-- ─────────────────────────────────────────────────────────────

-- Sessions where Chairman flagged departure (potential overreach signal)
CREATE VIEW IF NOT EXISTS v_chairman_departures AS
SELECT session_id, timestamp, user_prompt, chairman_synthesis
FROM council_sessions
WHERE chairman_departure_flagged = 1
ORDER BY timestamp DESC;

-- Sessions where panel reached consensus (no dissent surfaced)
CREATE VIEW IF NOT EXISTS v_consensus_sessions AS
SELECT session_id, timestamp, user_prompt
FROM council_sessions
WHERE dissent_present = 0 AND triage_decision = 'proceed'
ORDER BY timestamp DESC;

-- Cost summary by month
CREATE VIEW IF NOT EXISTS v_monthly_cost AS
SELECT
    strftime('%Y-%m', timestamp) AS month,
    COUNT(*) AS session_count,
    ROUND(SUM(estimated_cost_usd), 2) AS total_cost_usd,
    ROUND(AVG(estimated_cost_usd), 3) AS avg_cost_per_session,
    ROUND(MAX(estimated_cost_usd), 2) AS max_session_cost
FROM council_sessions
WHERE estimated_cost_usd IS NOT NULL
GROUP BY strftime('%Y-%m', timestamp)
ORDER BY month DESC;

-- Anonymization failure rate (for Tier 2 audits)
CREATE VIEW IF NOT EXISTS v_anonymization_accuracy AS
SELECT
    COUNT(*) AS total_audits,
    SUM(CASE WHEN correct = 1 THEN 1 ELSE 0 END) AS correct_guesses,
    ROUND(100.0 * SUM(CASE WHEN correct = 1 THEN 1 ELSE 0 END) / COUNT(*), 1) AS accuracy_pct,
    -- Above 25% (chance for 4 panelists) means anonymization is leaking
    CASE
        WHEN 100.0 * SUM(CASE WHEN correct = 1 THEN 1 ELSE 0 END) / COUNT(*) > 25.0
        THEN 'LEAKING — investigate'
        ELSE 'AT CHANCE — anonymization holding'
    END AS verdict
FROM anonymization_audits;
